[tools]
"cargo:jj-vine" = "0.4.0"
go = "latest"
jjui = "latest"
node = "latest"
ruby = "latest"
rust = "1.94"
usage = "latest"
uv = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
